name: Executar Robo
on:
  workflow_dispatch:

concurrency:
  group: automacao-assim-orbita
  cancel-in-progress: false

jobs:
  run-robo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: |
          npm install
          npx playwright install chromium

      - name: Executar robo
        run: node robo-v3.3.js
        env:
          SENHA: ${{ secrets.SENHA }}
          ORBITA_USER: ${{ secrets.ORBITA_USER }}
          ORBITA_PASS: ${{ secrets.ORBITA_PASS }}
          GOOGLE_SCRIPT_URL: ${{ secrets.GOOGLE_SCRIPT_URL }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Upload de Artefatos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-e-relatorios
          path: |
            logs/*.txt
            relatorios/*.xlsx
